// Question types for questionnaires
export type QuestionType = 'text' | 'multiline' | 'multiple_choice' | 'checkbox' | 'file_upload' | 'rating';

// Question category types
export type QuestionCategory = 'business_info' | 'project_goals' | 'design_preferences' | 'content' | 'technical';

// Individual question in a questionnaire
export interface QuestionnaireQuestion {
    id: string;
    templateId: string;
    question: string;
    type: QuestionType;
    options?: string[]; // For multiple choice and checkbox types
  required: boolean;
    order: number;
    category: QuestionCategory;
    createdAt: Date;
    updatedAt: Date;
}

// Questionnaire template
export interface QuestionnaireTemplate {
    id: string;
    createdByDesignerId: string;
    name: string;
    description: string;
    projectType: string; // e.g., 'website', 'branding', 'mobile_app', 'general'
  isPublic: boolean;
    questions: QuestionnaireQuestion[];
    createdAt: Date;
    updatedAt: Date;
}

// Client's answer to a single question
export interface ClientAnswer {
    questionId: string;
    question: string;
    answer: string | string[] | File[]; // Single answer, multiple answers, or file uploads
  type: QuestionType;
    category: QuestionCategory;
}

// Complete questionnaire response from a client
export interface QuestionnaireResponse {
    id: string;
    templateId: string;
    clientId: string;
    answers: ClientAnswer[]; // JSON stored as JSONB in database
  status: 'draft' | 'in_progress' | 'submitted' | 'reviewed';
    completenessScore?: number; // 0-100, calculated by AI
  followUpQuestions?: string[]; // Generated by AI analysis
  followUpsSent?: number; // Count of follow-up emails sent
  submittedAt?: Date;
    createdAt: Date;
    updatedAt: Date;
}

// AI Analysis result for questionnaire responses
export interface AIAnalysisResult {
    responseId: string;
    completenessScore: number; // 0-100
  incompleteAnswers: Array<{
      questionId: string;
      question: string;
      reason: string; // e.g., 'too vague', 'missing context', 'incomplete'
  }>;
    suggestedFollowUpQuestions: string[];
    insights: string[]; // Key insights about the project based on answers
  summary: string; // Brief summary of the project understanding
}

// Follow-up email metadata
export interface FollowUpEmail {
    id: string;
    responseId: string;
    clientId: string;
    designerId: string;
    subject: string;
    body: string;
    questions: string[]; // Specific questions requesting clarification
  sentAt: Date;
    respondedAt?: Date;
    status: 'pending' | 'sent' | 'bounced' | 'responded';
}

// Request types for API
export interface CreateTemplateRequest {
    type: 'template';
    name: string;
    description?: string;
    projectType?: string;
    isPublic?: boolean;
    createdByDesignerId: string;
    questions: Array<{
      question: string;
      type: QuestionType;
      options?: string[];
      required?: boolean;
      order: number;
      category: QuestionCategory;
    }>;
}

export interface SubmitResponseRequest {
    type: 'response';
    templateId: string;
    clientId: string;
    answers: ClientAnswer[];
}

export interface UpdateTemplateRequest {
    name?: string;
    description?: string;
    isPublic?: boolean;
    questions?: Array<{
      question: string;
      type: QuestionType;
      options?: string[];
      required?: boolean;
      order: number;
      category: QuestionCategory;
    }>;
}
